# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\brhnd\OneDrive\Masaüstü\movieDesigner.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1110, 776)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblPicture = QtWidgets.QLabel(self.centralwidget)
        self.lblPicture.setGeometry(QtCore.QRect(10, 100, 185, 278))
        self.lblPicture.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.lblPicture.setText("")
        self.lblPicture.setScaledContents(True)
        self.lblPicture.setObjectName("lblPicture")
        self.lblTitle = QtWidgets.QLabel(self.centralwidget)
        self.lblTitle.setGeometry(QtCore.QRect(210, 100, 741, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.lblTitle.setFont(font)
        self.lblTitle.setAutoFillBackground(False)
        self.lblTitle.setStyleSheet("text-decoration: underline;\n"
"color: rgb(170, 0, 0);")
        self.lblTitle.setObjectName("lblTitle")
        self.btnNextMovie = QtWidgets.QPushButton(self.centralwidget)
        self.btnNextMovie.setGeometry(QtCore.QRect(120, 390, 81, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnNextMovie.setFont(font)
        self.btnNextMovie.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnNextMovie.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.btnNextMovie.setObjectName("btnNextMovie")
        self.btnPreviousMovie = QtWidgets.QPushButton(self.centralwidget)
        self.btnPreviousMovie.setGeometry(QtCore.QRect(10, 390, 81, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btnPreviousMovie.setFont(font)
        self.btnPreviousMovie.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPreviousMovie.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.btnPreviousMovie.setObjectName("btnPreviousMovie")
        self.leName = QtWidgets.QLineEdit(self.centralwidget)
        self.leName.setGeometry(QtCore.QRect(10, 30, 941, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.leName.setFont(font)
        self.leName.setStyleSheet("border: 1px solid;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(170, 0, 0);")
        self.leName.setText("")
        self.leName.setObjectName("leName")
        self.lblStock = QtWidgets.QLabel(self.centralwidget)
        self.lblStock.setGeometry(QtCore.QRect(210, 150, 741, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lblStock.setFont(font)
        self.lblStock.setAutoFillBackground(False)
        self.lblStock.setStyleSheet("color: rgb(0, 0, 0);")
        self.lblStock.setObjectName("lblStock")
        self.teDescription = QtWidgets.QTextEdit(self.centralwidget)
        self.teDescription.setEnabled(True)
        self.teDescription.setGeometry(QtCore.QRect(10, 440, 941, 171))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.teDescription.setFont(font)
        self.teDescription.setReadOnly(True)
        self.teDescription.setObjectName("teDescription")
        self.lblInfos = QtWidgets.QLabel(self.centralwidget)
        self.lblInfos.setGeometry(QtCore.QRect(210, 210, 751, 221))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lblInfos.setFont(font)
        self.lblInfos.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblInfos.setAutoFillBackground(False)
        self.lblInfos.setStyleSheet("color: rgb(0, 0, 0);")
        self.lblInfos.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblInfos.setObjectName("lblInfos")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Recommendation"))
        self.lblTitle.setText(_translate("MainWindow", "<html><head/><body><p>Title</p></body></html>"))
        self.btnNextMovie.setToolTip(_translate("MainWindow", "Next movie"))
        self.btnNextMovie.setText(_translate("MainWindow", "Next"))
        self.btnPreviousMovie.setToolTip(_translate("MainWindow", "Previous movie"))
        self.btnPreviousMovie.setText(_translate("MainWindow", "Previous"))
        self.leName.setPlaceholderText(_translate("MainWindow", "Enter the movie name..."))
        self.lblStock.setText(_translate("MainWindow", "<html><head/><body><p>Stock</p></body></html>"))
        self.teDescription.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:400;\">Description</span></p></body></html>"))
        self.lblInfos.setText(_translate("MainWindow", "<html><head/><body><p>Infos</p></body></html>"))
